[plugin]
repository = "https://github.com/Arrenton/AudibleCharacterStatus.git"
commit = "ddd078f2fd18255ce35cb8c4bdec9f997dc17cc8"
owners = [
    "Arrenton",
]
changelog = """
Updated for API 10.
"""
