[plugin]
repository = "https://github.com/Arrenton/AudibleCharacterStatus.git"
commit = "6fedca6aba1946668d1bf0573ff648e9bea2a414"
owners = [
    "Arrenton",
]
changelog = """
Updated for API 10.
"""
